[package]
name = "solana-trading-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
solana-client = "1.10.24"
solana-sdk = "1.10.24"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }